In [1]:
import numpy as np

In [2]:
l = np.lcm.reduce(np.array([1,2,3]))
l

6

In [3]:
def myadd(x, y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [4]:
res = np.frompyfunc(lambda x,y: x+y,2,1)
res

<ufunc '<lambda> (vectorized)'>

In [8]:
print(type(np.concatenate))

<class 'function'>


In [9]:
print(type(np.blahblah))

AttributeError: module 'numpy' has no attribute 'blahblah'

In [10]:
print(type(np.add) == np.ufunc)

True


In [16]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

In [17]:
arr1+arr2

array([13, 27, 39, 48, 52, 93])

In [19]:
arr1+4

array([14, 24, 34, 44, 54, 64])

In [20]:
arr1%arr2

array([ 1,  6,  3,  0,  0, 27], dtype=int32)